### ISSUE TITLE
[FEATURE] Run as portage support

### ISSUE THREAD

**Issue by ncdulo** [ncdulo/portop#3]
**Is your feature request related to a problem? Please describe.**
To be a little more secure, or less likely to break the system, we may not necessarily need to run as root. So long as the commands, or files in question are owned in some capacity by `portage`, we should be alright to `sudo -u portage` when running this program.

**Describe the solution you'd like**
Update the `if` block to include a check for `(effective user id == 0) OR (effective user id == 250)`. Group 250 should always refer to `portage` on Gentoo systems by default. There may also be a way to determine the number automatically. Automatic detection is likely preferred, I think.

**Describe alternatives you've considered**
Run as root, always. This works just fine. But requires the user have permission to `sudo` as root. Most cases this is just fine but let's give the option to the user. Running with as few permissions as necessary is always a sensible choice.

**Additional context**
I had attempted to implement this from the start without results. Simply put, my bash-fu is not up to par at the moment. We'll get it.

**Comment by Phate6660** [comment]
Note: If checking for multiple IDs, a `case` statement would be preferable to multiple `if` statements.

For example:

```bash
case "$(id -u)" in
    0) continue;;
    250) continue;;
    *) echo "Must be run as portage or root!" && exit 1;;
esac
```

vs

```bash
id="$(id -u)"
if [ "$id" = 0 ]; then
    continue
elif [ "$id" = 250 ]; then
    continue
else
    echo "Must be run as portage or root!" && exit 1
fi
````

Even with just 2 id checks the potential for extra/unneeded script is high.

**Comment by ncdulo** [comment]
The first case statement looks like it would work perfectly. Did not even think of that, even while looking past some case statement examples today. I'll get that written up and committed shortly. Thank you!
